apiVersion: v1
kind: Service
metadata:
  name: picosite
  labels:
    app: picosite
spec:
  ports:
    - port: 80
      targetPort: http-server
  selector:
    app: picosite
  type: LoadBalancer # LoadBalancer | NodePort